apiVersion: v1
kind: Service
metadata:
  name: svc-demo-v1
  labels:
    app: demo
    version: v1
spec:
  type: ClusterIP
  selector:
    app: demo
    version: v1
  ports:
    - port: 80
      targetPort: 8080
