apiVersion: v1
kind: Service
metadata:
  name: svc-demo-v2
  labels:
    app: demo
    version: v2
spec:
  type: ClusterIP
  selector:
    app: demo
    version: v2
  ports:
    - port: 80
      targetPort: 8080
