# demo-stable-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: demo-stable
  namespace: canary-tp
spec:
  selector:
    app: demo
    version: v1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
