# demo-canary-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: demo-canary
  namespace: canary-tp
spec:
  selector:
    app: demo
    version: v2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
